name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Install typescript
        run: npm install typescript
      - name: Publish package
        run: |
          npm install
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config list
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}